Repository TabbycatDebate/tabbycat, pull requests merged in 2020-01, with the labels that each got.

#1353 Use pre-commit for flake8 hook
  .pre-commit-config.yaml
  .travis.yml
  CONTRIBUTING.rst
  config/requirements_development.txt
Labels: dependency, question/discussion

#1226 Fixup manageidentifiers command
  tabbycat/checkins/management/commands/manageidentifiers.py
  tabbycat/checkins/utils.py
Labels: awaiting maintainer

#1351 Tournament endpoints and hyperlinked API
  tabbycat/api/fields.py
  tabbycat/api/serializers.py
  tabbycat/api/urls.py
  tabbycat/api/views.py
  tabbycat/tournaments/mixins.py
Labels: api
